### ISSUE TITLE
Kickstart - Developer creation step isn't idempotent 

### ISSUE THREAD

**Issue by laughingbiscuit** [mikesson/apigee-mint-node#3]
If I run the kickstart twice in a row, some of the entities have already been created. For most steps, if the entity exists then we skip it, but this isn't true for developers. Instead we see...

```
error: ✖ Developer with email "developer@organization.com" already exists
info: ▶ Tip: Change the developer email in the "9-developer.yml" config file as it needs to be unique
error: ◼ [kickstart setup failed]
```

Could we skip developer creation if they existing?

**Comment by mikesson** [comment]
Developer account is now reused instead of error being raised, hence does not require to create new developer accounts per kickstart script execution. Fixed with commit 77949c10b1b5018d667f944fe3327941c863f0e5
