### ISSUE TITLE
Kickstart - If deployment fails, error isn't displayed correctly

### ISSUE THREAD

**Issue by laughingbiscuit** [mikesson/apigee-mint-node#4]
```
info: ✔︎ Balance added to developer account
debug: selected proxy directory: /home/davissean/apigee-mint-node/proxies
info: Deploying proxy ...
⠇ error: ✖ Proxy Deployment failed - see error below:
error: {}
error: ◼ [kickstart setup failed]

```

**Comment by mikesson** [comment]
error message for deploy errors now displaying. For VHost errors in specific, troubleshooting tips have been added. 
![image](https://user-images.githubusercontent.com/5867979/71664652-998d5a00-2d51-11ea-8553-9edf876260fd.png)

fixed in commit 8e10ee5a41270e933376e32d7877d6c227cf66bd
