### ISSUE TITLE
Kickstart - assumes that the organization has a virtual host called 'secure'

### ISSUE THREAD

**Issue by laughingbiscuit** [mikesson/apigee-mint-node#5]
It would be nice to specify the name of the vhost or give a better error message on failure.

I see:
```
⠏ error: ✖ Proxy Deployment failed - see error below:
error: {}
error: ◼ [kickstart setup failed]
```

**Comment by mikesson** [comment]
since commit 8e10ee5a41270e933376e32d7877d6c227cf66bd , deploy error now shows the correct message with tips on "invalid vHost" and where to change the host in the xml. When using with OPDK, proxy config can be changed to point to existing vHost names.
