### ISSUE TITLE
Kickstart proxy uses a spec from the spec store 

### ISSUE THREAD

**Issue by laughingbiscuit** [mikesson/apigee-mint-node#6]
`association.json`
```
{
	"url": "/c3Rvc-ZG9j-29513/content"
}
```

this isn't supported in OPDK - maybe we could switch this to use a proxy that doesnt need the spec store.

**Comment by mikesson** [comment]
Fixed through removing the spec reference, to support both OPDK and Cloud, in latest commit (38b8819da44e76b49b734d62c0223ed0884bdfb8).
